version: "3.9"
services: 
  blazor: 
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      BuildConfiguration: Release
    ports: 
    - "443:443"
    - "80:80"
    restart: always