on:
  workflow_call:
    inputs:
      source:
        required: true
        type: string
      destination:
        required: true
        type: string

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ${{ inputs.source }}
          destination: ${{ inputs.destination }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1