name: Build branch
on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
    - feature/*
    - master 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  oidc_token: 
    runs-on: ubuntu-latest
    outputs: 
      staticWebAppOIDCToken: ${{ steps.export_id_token.outputs.idtoken }}
    steps:
      - name: Install OIDC Client from Core Package
        run: npm install @actions/core@1.6.0 @actions/http-client
      - name: Get Id Token
        uses: actions/github-script@v6
        id: generate_id_token
        with:
          script: |
            const actions_core = require('@actions/core');
            const idToken = await actions_core.getIDToken();
            actions_core.setOutput("id_token", idToken);
            console.log(`id_token=${idToken}`);
      - name: Export Id Token to ENV
        id: export_id_token
        run: echo "ID_TOKEN=${{ steps.idtoken.outputs.id_token }}" >> $GITHUB_ENV

  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      - name: Install Dotnet Wasm Tools
        run: dotnet workload install wasm-tools
      - name: Npm Install
        working-directory: MysteryMystery.github.io
        run: npm install
      - name: Dotnet Restore
        working-directory: MysteryMystery.github.io
        run: dotnet restore
      - name: Dotnet Test
        working-directory: MysteryMystery.github.io
        run: dotnet test
      - name: Dotnet Publish
        working-directory: MysteryMystery.github.io
        run: dotnet publish -c Release --nologo
      - name: copy index.html to 404.html
        run: cp bin/Release/net8.0/publish/wwwroot/index.html bin/Release/net8.0/publish/wwwroot/404.html
        working-directory: MysteryMystery.github.io/MysteryMystery.github.io
      - name: Add .nojekyll file
        run: touch bin/Release/net8.0/publish/wwwroot/.nojekyll
        working-directory: MysteryMystery.github.io/MysteryMystery.github.io
      - uses: actions/upload-artifact@v3
        with:
          name: mysterymysterygithubio
          path: MysteryMystery.github.io/MysteryMystery.github.io/bin/Release/net8.0/publish/

  semver:
    needs: build # Only tag if the build is successful
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          major_regexp_flags: ""
          minor_pattern: "(MINOR)"
          minor_regexp_flags: ""
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          change_path: "MysteryMystery.github.io"
          namespace: portfolio
          bump_each_commit: false
          bump_each_commit_patch_pattern: ""
          search_commit_body: false
          user_format_type: "csv"
          enable_prerelease_mode: true
          debug: true
          version_from_branch: false

  deployStaging: 
    needs: 
      - oidc_token
      - build 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/download-artifact@v3
        with:
          name: mysterymysterygithubio
          path: deploy
      - name: Deploy to Static Web App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_CLIFF_07B6A5203 }}
          action: "upload"
          app_location: "deploy/wwwroot"
          github_id_token: ${{ needs.oidc_token.outputs.staticWebAppOIDCToken }}
          skip_app_build: true

  deployProduction:
    needs: 
     - build 
     - deployStaging
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: mysterymysterygithubio
          path: deploy
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: deploy/wwwroot