# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build branch
on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
    - feature/*
    - master 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  #pages: write
  #id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  TF_CLOUD_ORGANIZATION: "MysteryMystery123"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "Production"
  SUBSCRIPTION_ID: "${{ secrets.SUBSCRIPTION_ID }}"

jobs:
  terraform_plan: 
    #if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: terraform/azure
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: terraform/azure

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=${{env.GITHUB_OUTPUT}}/out.tfplan -var "subscription_id=${{ env.SUBSCRIPTION_ID }}" -var "environment=prd"
        working-directory: terraform/azure
      
      - uses: actions/upload-artifact@master
        with:
          name: tf_out
          path: ${{env.GITHUB_OUTPUT}}/out.tfplan
      
  
  terraform_apply:
    if: github.ref == 'refs/heads/master'
    needs: terraform_plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: tf_out
          path: ${{env.GITHUB_OUTPUT}}
      
      - name: Terraform Init
        id: init
        run: terraform init    
        working-directory: terraform/azure

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false -var "subscription_id=${{ env.SUBSCRIPTION_ID }}" -var "environment=prd" ${{env.GITHUB_OUTPUT}}/out.tfplan
        working-directory: terraform/azure

  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '19'
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
      - name: Compile Tailwind
        working-directory: Blazor/Blazor
        run: npx tailwindcss -i ./Css/app.css -o ./wwwroot/css/app.css --minify
      - name: Dotnet Restore
        working-directory: Blazor
        run: dotnet restore
      - name: Dotnet Test
        working-directory: Blazor
        run: dotnet test
      - name: Dotnet Publish
        working-directory: Blazor
        run: dotnet publish -c Release --nologo
      - name: copy index.html to 404.html
        run: cp bin/Release/net6.0/publish/wwwroot/index.html bin/Release/net6.0/publish/wwwroot/404.html
        working-directory: Blazor/Blazor
      - name: Add .nojekyll file
        run: touch bin/Release/net6.0/publish/wwwroot/.nojekyll
        working-directory: Blazor/Blazor
      - uses: actions/upload-artifact@master
        with:
          name: mysterymysterygithubio
          path: Blazor/Blazor/bin/Release/net6.0/publish/

# deploy if master
  deploy:
    needs: build_frontend
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: mysterymysterygithubio
          path: deploy
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: deploy/wwwroot